// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_KkVSjteVNKhJS2KbtNba4NwITb45nXk',
    appId: '1:174489772790:web:4906aa8a17bdd6032d02d7',
    messagingSenderId: '174489772790',
    projectId: 'quickplate-dda80',
    authDomain: 'quickplate-dda80.firebaseapp.com',
    storageBucket: 'quickplate-dda80.appspot.com',
    measurementId: 'G-B7Z9GF0Z29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSZn1bZNBQEpxwbaV-dNNe79AHdjwt3F8',
    appId: '1:174489772790:android:cca55f6ca350b44f2d02d7',
    messagingSenderId: '174489772790',
    projectId: 'quickplate-dda80',
    storageBucket: 'quickplate-dda80.appspot.com',
  );
}
